/* GENERATED by tools/genregs.py from the schemas in registers/ -- DO NOT EDIT.
 *
 * Edit the schema and regenerate. CI runs `genregs.py --check` and fails the
 * build if this file has drifted from the schema, so a hand-edit here does not
 * survive; it just breaks the build later and further from the cause.
 *
 * The static_asserts below are the point of this file. The generator computes
 * offsets from the schema; these make the COMPILER check that arithmetic against
 * what it actually lays out. Emitting both sides of the link from one source is
 * only trustworthy because this disagreement is a build failure.
 */

#ifndef RAMPS_GENERATED_H
#define RAMPS_GENERATED_H

#include <assert.h>
#include <stddef.h>
#include <stdint.h>

/* static_assert, not _Static_assert: parts of the emulator suite compile
 * this header as C++, where _Static_assert does not exist and the errors
 * are unhelpful ("expected constructor, destructor, or type conversion").
 * <assert.h> defines static_assert for C11 and it is a keyword in C++11,
 * so this one spelling works for the ARM build, the host C build and the
 * C++ translation units alike. */

#ifndef ELS_DIAG_TRACE_BUCKETS
#define ELS_DIAG_TRACE_BUCKETS 50  /* verified against fw/Core/Inc/Ramps.h */
#endif
#ifndef SCALES_COUNT
#define SCALES_COUNT 4  /* verified against fw/Core/Inc/Scales.h */
#endif


/* ======== servo_t -- from registers/servo.yaml ======== */

#define SERVO_TOTAL_REGS 18u
#define SERVO_ALL_REG_BASE 0u
#define SERVO_ALL_REG_COUNT 18u

/* servo_t occupies registers 8..25 of rampsSharedData_t. */
typedef struct {

  /* ---- ALL ----
   * The whole struct. Servo configuration and live ramp state; the tick-rate
   * mirrors of the live values are in fastData_t.
   */
  float maxSpeed;                                   /* reg 0  SW write: maximum step rate (steps/s); clamped to 100000 by firmware */

  /* reg 2 READ-ONLY (firmware-owned): live ramp speed, managed by ramp
   * algorithm
   */
  float currentSpeed;
  float jogSpeed;                                   /* reg 4  SW write: jog target speed (steps/s); negative = reverse */
  float acceleration;                               /* reg 6  SW write: ramp acceleration (steps/s²) */

  /* reg 8 SW write: remaining steps for indexing move; firmware decrements
   * toward zero
   */
  int32_t stepsToGo;

  /* reg 10 SW write: absolute destination step count for indexing mode
   */
  uint32_t destinationSteps;

  /* reg 12 READ-ONLY (firmware-owned): step counter incremented/decremented
   * by ISR
   */
  uint32_t currentSteps;

  /* reg 14 READ-ONLY (firmware-owned): accumulated target steps, driven by
   * sync/ramp
   */
  uint32_t desiredSteps;

  /* reg 16 SW write: ±1, default +1 (no inversion); applied to DIR pin in ISR
   */
  int16_t servoDir;
  /* 2 bytes of IMPLICIT tail padding (reg 17): sizeof rounds up to
   * the struct's 4-byte alignment. Pinned by the sizeof assert below. */
} servo_t;

/* ---- the compiler's vote ---- */
static_assert(offsetof(servo_t, maxSpeed) == 0, "maxSpeed moved: schema says register 0");
static_assert(offsetof(servo_t, currentSpeed) == 4, "currentSpeed moved: schema says register 2");
static_assert(offsetof(servo_t, jogSpeed) == 8, "jogSpeed moved: schema says register 4");
static_assert(offsetof(servo_t, acceleration) == 12, "acceleration moved: schema says register 6");
static_assert(offsetof(servo_t, stepsToGo) == 16, "stepsToGo moved: schema says register 8");
static_assert(offsetof(servo_t, destinationSteps) == 20, "destinationSteps moved: schema says register 10");
static_assert(offsetof(servo_t, currentSteps) == 24, "currentSteps moved: schema says register 12");
static_assert(offsetof(servo_t, desiredSteps) == 28, "desiredSteps moved: schema says register 14");
static_assert(offsetof(servo_t, servoDir) == 32, "servoDir moved: schema says register 16");
static_assert(sizeof(servo_t) == 36, "servo_t is not 18 registers");
static_assert(SERVO_ALL_REG_COUNT <= 125, "all group exceeds its FC3 request budget");


/* ======== input_t -- from registers/input.yaml ======== */

#define INPUT_TOTAL_REGS 12u
#define INPUT_ALL_REG_BASE 0u
#define INPUT_ALL_REG_COUNT 12u

/* input_t is scales[SCALES_COUNT] of rampsSharedData_t: element i occupies
 * registers 26 + 12*i, 4 elements, 26..73 in all. */
typedef struct {

  /* ---- ALL ----
   * The whole struct: one scale's encoder state and its sync configuration.
   */

  /* reg 0 init-only: index into ramps_timer_handles[]; held as a 4-byte slot
   * id (not a pointer) so the modbus wire layout is identical on STM32 and
   * 64-bit emulator hosts
   */
  uint32_t timerHandleSlot;

  /* reg 2 READ-ONLY (firmware-owned): absolute encoder position, updated by
   * ISR
   */
  int32_t position;

  /* reg 4 READ-ONLY (firmware-owned): encoder speed (counts/s), updated by
   * updateSpeedTask
   */
  int32_t speed;

  /* reg 6 SW write: sync ratio numerator/denominator (output steps per input
   * count)
   */
  int32_t syncRatioNum;

  /* reg 8 SW write: sync ratio numerator/denominator (output steps per input
   * count)
   */
  int32_t syncRatioDen;

  /* reg 10 SW write: 0 = sync disabled, non-zero = sync enabled for this
   * scale
   */
  uint16_t syncEnable;

  /* reg 11 SW write: ±1, default +1 (no inversion); applied to encoder delta
   * in ISR
   */
  int16_t scaleDir;
} input_t;

/* ---- the compiler's vote ---- */
static_assert(offsetof(input_t, timerHandleSlot) == 0, "timerHandleSlot moved: schema says register 0");
static_assert(offsetof(input_t, position) == 4, "position moved: schema says register 2");
static_assert(offsetof(input_t, speed) == 8, "speed moved: schema says register 4");
static_assert(offsetof(input_t, syncRatioNum) == 12, "syncRatioNum moved: schema says register 6");
static_assert(offsetof(input_t, syncRatioDen) == 16, "syncRatioDen moved: schema says register 8");
static_assert(offsetof(input_t, syncEnable) == 20, "syncEnable moved: schema says register 10");
static_assert(offsetof(input_t, scaleDir) == 22, "scaleDir moved: schema says register 11");
static_assert(sizeof(input_t) == 24, "input_t is not 12 registers");
static_assert(INPUT_ALL_REG_COUNT <= 125, "all group exceeds its FC3 request budget");


/* ======== fastData_t -- from registers/fast_data.yaml ======== */

#define FAST_DATA_TOTAL_REGS 30u
#define FAST_DATA_ALL_REG_BASE 0u
#define FAST_DATA_ALL_REG_COUNT 30u

/* fastData_t occupies registers 74..103 of rampsSharedData_t. */
typedef struct {

  /* ---- ALL ----
   * The whole struct. Firmware-published mirrors of the live servo and scale
   * state, refreshed by the ISR and updateSpeedTask, plus the servo mode.
   * Read as one request per board tick.
   */

  /* reg 0 READ-ONLY (firmware-owned): mirror of servo.currentSteps, updated
   * by updateSpeedTask
   */
  uint32_t servoCurrent;

  /* reg 2 READ-ONLY (firmware-owned): mirror of servo.desiredSteps, updated
   * by updateSpeedTask
   */
  uint32_t servoDesired;

  /* reg 4 READ-ONLY (firmware-owned): mirror of servo.stepsToGo, updated by
   * ramp algorithm
   */
  uint32_t stepsToGo;

  /* reg 6 READ-ONLY (firmware-owned): output step rate (steps/100ms), updated
   * by servoEnableTask
   */
  float servoSpeed;

  /* reg 8 READ-ONLY (firmware-owned): mirror of scales[i].position, updated
   * by ISR
   */
  int32_t scaleCurrent[SCALES_COUNT];

  /* reg 16 READ-ONLY (firmware-owned): mirror of scales[i].speed, updated by
   * updateSpeedTask
   */
  int32_t scaleSpeed[SCALES_COUNT];

  /* reg 24 READ-ONLY (firmware-owned): ISR execution time in CPU cycles,
   * updated by updateSpeedTask
   */
  uint32_t cycles;

  /* reg 26 READ-ONLY (firmware-owned): ISR interval in CPU cycles, updated by
   * ISR
   */
  uint32_t executionInterval;

  /* reg 28 SW write: 0=disabled, 1=sync/index (also set by firmware), 2=jog
   */
  uint16_t servoMode;
  /* 2 bytes of IMPLICIT tail padding (reg 29): sizeof rounds up to
   * the struct's 4-byte alignment. Pinned by the sizeof assert below. */
} fastData_t;

/* ---- the compiler's vote ---- */
static_assert(offsetof(fastData_t, servoCurrent) == 0, "servoCurrent moved: schema says register 0");
static_assert(offsetof(fastData_t, servoDesired) == 4, "servoDesired moved: schema says register 2");
static_assert(offsetof(fastData_t, stepsToGo) == 8, "stepsToGo moved: schema says register 4");
static_assert(offsetof(fastData_t, servoSpeed) == 12, "servoSpeed moved: schema says register 6");
static_assert(offsetof(fastData_t, scaleCurrent) == 16, "scaleCurrent moved: schema says register 8");
static_assert(offsetof(fastData_t, scaleSpeed) == 32, "scaleSpeed moved: schema says register 16");
static_assert(offsetof(fastData_t, cycles) == 48, "cycles moved: schema says register 24");
static_assert(offsetof(fastData_t, executionInterval) == 52, "executionInterval moved: schema says register 26");
static_assert(offsetof(fastData_t, servoMode) == 56, "servoMode moved: schema says register 28");
static_assert(sizeof(fastData_t) == 60, "fastData_t is not 30 registers");
static_assert(FAST_DATA_ALL_REG_COUNT <= 75, "all group exceeds its FC3 request budget");


/* ======== elsStop_t -- from registers/els_stop.yaml ======== */

#define ELS_STOP_PROTOCOL_VERSION 10u
#define ELS_STOP_TOTAL_REGS 142u
#define ELS_STOP_HOT_REG_BASE 0u
#define ELS_STOP_HOT_REG_COUNT 56u
#define ELS_STOP_COLD_REG_BASE 56u
#define ELS_STOP_COLD_REG_COUNT 86u

/* elsStop_t occupies registers 104..245 of rampsSharedData_t. */
typedef struct {

  /* ---- HOT ----
   * Read as ONE FC3 request every board tick (30 Hz) by
   * Board._refresh_els_stop_snapshot. The quantity being minimised is
   * REQUESTS, not bytes -- each request is an independent chance for the
   * firmware to miss its answering window while the motion ISR is saturated
   * (2026-08-23: six of six cuts lost comms, every drop a timeout). That
   * measurement was taken at the old 100 kHz tick; the ISR has run at 50 kHz
   * since 2026-08-28, which relieves the pressure without changing the
   * argument.
   */
  uint16_t enable;                                  /* reg 0  SW write: 1 = enable ELS stop feature */
  uint16_t scaleIndex;                              /* reg 1  SW write: which scale (0–3) is the position reference (Z axis) */
  int32_t stopPosition;                             /* reg 2  SW write: threshold in encoder counts */

  /* reg 4 SW write: 1 = stop when pos >= threshold, -1 = stop when pos <=
   * threshold
   */
  int16_t stopDirection;

  /* reg 5 bidirectional: firmware sets to 1 when triggered; SW writes 0 to
   * resume
   */
  uint16_t active;

  /* reg 6 SW write: leadscrew steps per thread pitch (float); 0.0f = turning
   * (no correction)
   */
  float threadPitchSteps;

  /* reg 8 SW write: encoder counts carriage must retract before re-enabling;
   * 0 = no hysteresis
   */
  int32_t hysteresis;

  /* reg 10 SW write: Z scale encoder counts per thread pitch; 0.0f =
   * correction disabled
   */
  float zCountsPerPitch;

  /* reg 12 SW write: leadscrew backlash takeup magnitude in servo steps;
   * direction derived from sign(syncRatioNum) × sign(threadPitchSteps ×
   * zCountsPerPitch); 0 = takeup disabled
   */
  uint32_t backlashSteps;

  /* reg 14 READ-ONLY (firmware-owned): scales[scaleIndex].position at first
   * trigger of the job
   */
  int32_t latchedZ;

  /* reg 16 READ-ONLY (firmware-owned): scales[0].position at first trigger of
   * the job
   */
  int32_t latchedSpindle;

  /* reg 18 READ-ONLY (firmware-owned): 0 until first trigger captures the
   * reference, 1 thereafter; reset on enable 0→1
   */
  uint16_t referenceLatched;

  /* reg 19 READ-ONLY (firmware-owned): 1 while the backlash take-up that
   * starts EVERY pass (first pass and turning included since 2026-08-21) is
   * executing or awaiting Z confirmation; gates sync off meanwhile
   */
  uint16_t takeupPending;

  /* reg 20 READ-ONLY (firmware-owned): last resume's deltaSpindle ×
   * syncRatioNum / syncRatioDen
   */
  float lastIdealAdvance;

  /* reg 22 READ-ONLY (firmware-owned): last resume's deltaZ ×
   * threadPitchSteps / zCountsPerPitch
   */
  float lastActualAdvance;

  /* reg 24 READ-ONLY (firmware-owned): last resume's idealAdvance −
   * actualAdvance (pre-modulo)
   */
  float lastPhaseError;

  /* reg 26 READ-ONLY (firmware-owned): last resume's correction added to
   * stepsToGo (post-modulo)
   */
  float lastCorrection;

  /* reg 28 READ-ONLY (firmware-owned): register-layout version, starts at 1.
   * Bump whenever this struct changes; reflex-ui checks it at connect so a
   * map mismatch names itself instead of surfacing as garbled reads
   */
  uint16_t protocolVersion;

  /* reg 29 READ-ONLY (firmware-owned): increments once per take-up outcome;
   * lets SW tell completed-normally from host-cleared, which takeupPending
   * alone cannot Monotonic ack; edge-detect it. Sits below everything it
   * counts.
   */
  uint16_t takeupSeq;

  /* reg 30 READ-ONLY (firmware-owned): outcome of the last take-up. ELS_CAL_*
   * /ELS_TAKEUP_* in els_backlash_cal.h; 0 = OK. Replaces a binary fault flag
   * so "carriage never moved" and "never reached target" stay distinguishable
   */
  uint16_t takeupResult;
  uint16_t _pad1;        /* generator-emitted alignment, before lastTakeupZDelta */

  /* reg 32 READ-ONLY (firmware-owned): signed Z counts moved across the last
   * take-up, projected onto the take-up direction. NEGATIVE means the
   * carriage moved the WRONG way — a distinct fault signature from "didn't
   * move"
   */
  int32_t lastTakeupZDelta;

  /* reg 34 READ-ONLY (firmware-DERIVED, not operator-set): Z counts the last
   * take-up had to move to be confirmed. Derived from (backlashSteps -
   * mean(calMeasured)) via elsTakeupConfirmThreshold(); falls back to
   * calMotionThreshCounts with no calibration on file or in turning mode.
   * Published so the UI can say "moved 3, needed 4" instead of just refusing
   */
  int32_t takeupThreshCounts;

  /* reg 36 READ-ONLY except for reset: narrowest STEP pulse since host wrote
   * 0. 0 = nothing measured yet
   */
  uint32_t stepPulseMinCycles;

  /* reg 38 READ-ONLY except for reset: pulses narrower than
   * ELS_STEP_RUNT_CYCLES since host wrote 0
   */
  uint32_t stepPulseRuntCount;

  /* reg 40 READ-ONLY (firmware-owned): increments once per COMPLETED capture.
   * Edge-detect this; there is deliberately no "capture in progress" register
   * to poll. ORDERING INVARIANT: must stay at a LOWER address than the
   * capture payload it counts -- see the calSeq comment above for why a
   * reorder reintroduces the torn-read bug Monotonic ack; edge-detect it.
   * Sits below everything it counts.
   */
  uint16_t diagSeq;

  /* reg 41 READ-ONLY (firmware-owned): ELS_MMODE_* (els_machine_mode.h),
   * republished every servoEnableTask tick in every build
   */
  uint16_t machineMode;

  /* reg 42 READ-ONLY (firmware-owned): increments once per ACCEPTED manual
   * latch. Monotonic; the ack for latchCommand Monotonic ack; edge-detect it.
   * Sits below everything it counts.
   */
  uint16_t latchSeq;

  /* reg 43 READ-ONLY (firmware-owned): increments once per ACCEPTED apply.
   * Monotonic; the ack for phaseOffsetCommand Monotonic ack; edge-detect it.
   * Sits below everything it counts.
   */
  uint16_t phaseOffsetSeq;

  /* reg 44 READ-ONLY (firmware-owned): the live cumulative total in leadscrew
   * steps, applied at every phase correction. Cleared on the enable 0->1 edge
   * that clears referenceLatched -- an offset is meaningless without the
   * datum it offsets -- and survives per-pass stop/resume within a job
   */
  int32_t phaseOffsetSteps;

  /* reg 46 READ-ONLY (firmware-owned): increments once per stop trigger,
   * immediately BEFORE the payload below. Monotonic; edge-detect it, and
   * re-read on no edge Monotonic ack; edge-detect it. Sits below everything
   * it counts.
   */
  uint16_t stopTriggerSeq;
  uint16_t _pad2;        /* generator-emitted alignment, before stopTriggerZ */

  /* reg 48 READ-ONLY (firmware-owned): scales[scaleIndex].position at the
   * trigger, and it is the SAME value the threshold comparison was made on,
   * not a re-read. (settled Z) - this = the coast. NOTE it is the reference
   * scale as of the PREVIOUS tick when scaleIndex is above the sync-enabled
   * scale's index -- the trigger test runs inside that scale's loop
   * iteration, before this one's position is updated. 10 us of lag, inherent
   * to the DECISION rather than to this register (latchedZ has always had
   * it), and the right endpoint precisely because overshoot is measured from
   * where the firmware decided to stop
   */
  int32_t stopTriggerZ;

  /* reg 50 READ-ONLY (firmware-owned): scales[scaleIndex].speed at the
   * trigger, encoder counts/s -- the same register and units the DRO shows.
   * The table's x-axis. Computed by updateSpeedTask over the 50 ms window
   * ENDING BEFORE the trigger, so unlike a host estimate it cannot straddle
   * the coast; it is up to 50 ms old, which on a constant-feed threading pass
   * is the steady approach speed and is exactly what is wanted
   */
  int32_t stopTriggerZSpeed;

  /* reg 52 READ-ONLY (firmware-owned): servo.stepsToGo at the trigger.
   * NONZERO means the firmware was still commanding motion, so the overshoot
   * is not purely mechanical coast -- the 2026-08-28 stop-overshoot captures
   * found zero emitted steps after the trigger in 12 of 14 passes, and this
   * makes that check automatic per pass instead of a one-off probe build
   */
  int32_t stopTriggerStepsToGo;

  /* reg 54 READ-ONLY (firmware-owned): scales[0].speed at the trigger,
   * counts/s. Context, and enough for a host to reconstruct the commanded
   * feed of a threading pass from the sync ratio
   */
  int32_t stopTriggerSpindleSpeed;

  /* ---- COLD ----
   * Never read on the tick path. Fetched on demand -- at connect, after a
   * calibration run, or when a diagnostic build is being read out.
   */

  /* reg 56 bidirectional: SW writes 1 to request a calibration run; FIRMWARE
   * CLEARS IT on consume. This is the atomic hand-off. SW must NOT poll it
   * for completion — it clears the instant the ISR picks it up, long before
   * the run finishes. Edge-detect calSeq instead CLEARED BY FIRMWARE ON
   * CONSUME -- poll calSeq, never this.
   */
  uint16_t calCommand;

  /* reg 57 READ-ONLY (firmware-owned): increments once per finished run,
   * success OR failure. Monotonic, so a host polling at Modbus rates cannot
   * alias a fast run Monotonic ack; edge-detect it. Sits below everything it
   * counts.
   */
  uint16_t calSeq;

  /* reg 58 READ-ONLY (firmware-owned): outcome of the run counted by calSeq.
   * ELS_CAL_* in els_backlash_cal.h; 0 = OK
   */
  uint16_t calResult;

  /* reg 59 bidirectional: SW writes 1 to request a manual reference latch;
   * FIRMWARE CLEARS IT on consume. Consumed ONLY while enable == 1 (a
   * reference is meaningless outside a job and would be wiped by the next
   * enable 0->1 anyway); when enable == 0 it is cleared with NO latchSeq
   * increment, so an absent ack IS the refusal. SW must edge-detect latchSeq,
   * never poll this CLEARED BY FIRMWARE ON CONSUME -- poll latchSeq, never
   * this.
   */
  uint16_t latchCommand;

  /* reg 60 bidirectional: SW writes 1 to apply phaseOffsetPending as the new
   * total; FIRMWARE CLEARS IT on consume. Not a completion flag --
   * edge-detect phaseOffsetSeq CLEARED BY FIRMWARE ON CONSUME -- poll
   * phaseOffsetSeq, never this.
   */
  uint16_t phaseOffsetCommand;
  uint16_t _pad3;        /* generator-emitted alignment, before phaseOffsetPending */

  /* reg 62 host-written candidate total, leadscrew steps. Read by the ISR
   * ONLY under a nonzero phaseOffsetCommand; write it BEFORE the command,
   * never after
   */
  int32_t phaseOffsetPending;

  /* reg 64 bidirectional: SW writes ELS_BOOT_CMD_* (els_identity.h); FIRMWARE
   * CLEARS IT on consume. 1 = reboot into the bootloader and stay resident, 2
   * = plain reboot. Refused (cleared, no ack) while enable != 0 CLEARED BY
   * FIRMWARE ON CONSUME -- poll bootSeq, never this.
   */
  uint16_t bootCommand;

  /* reg 65 READ-ONLY (firmware-owned): increments once per ACCEPTED boot
   * command, immediately before the reset it triggers Monotonic ack;
   * edge-detect it. Sits below everything it counts.
   */
  uint16_t bootSeq;

  /* reg 66 READ-ONLY (firmware-owned): lash measured at each of the 3
   * reversals, in servo steps. The HOST judges whether the spread is
   * acceptable — measurement lives here, policy lives in the UI
   */
  int32_t calMeasured[3];

  /* reg 72 SW write: per-leg hard ceiling in servo steps. Driving this far
   * without Z moving IS the open-half-nut / uncoupled failure.
   * MACHINE-SPECIFIC; size it comfortably past the largest credible lash
   */
  int32_t calCeilingSteps;

  /* reg 74 SW write: Z scale counts that count as real motion.
   * MACHINE-SPECIFIC — ~2 counts on elspi (200 counts/mm, so 1 count ≈ 2.5
   * servo steps); emulator is 400 counts/mm. 0 disables detection and FAILS
   * CLOSED (never confirms) — deliberate: an unconfigured threshold must
   * refuse, not wave everything through
   */
  int32_t calMotionThreshCounts;

  /* reg 76 READ-ONLY except for reset: highest executionCycles since the host
   * last wrote 0 here. Compare against 1000 (the per-tick budget at 100 MHz /
   * 10 us)
   */
  uint32_t executionCyclesPeak;

  /* reg 78 READ-ONLY (firmware-owned): identifies the probe compiled into the
   * block. 0 = none; do NOT interpret anything below it. Never assume a
   * schema you did not read
   */
  uint16_t diagSchema;

  /* reg 79 READ-ONLY (firmware-owned): ISR ticks summed into each diagTrace
   * bucket. PUBLISHED so the host never has to assume the ISR rate — the repo
   * has disagreed with itself about that rate by 10x
   */
  uint16_t diagBucketTicks;

  /* reg 80 READ-ONLY (firmware-owned): populated diagTrace entries, for the
   * same reason
   */
  uint16_t diagBucketCount;
  uint16_t _pad4;        /* generator-emitted alignment, before diagSettleTicks */

  /* reg 82 READ-ONLY (firmware-owned): ticks from capture start to the LAST
   * tick that saw nonzero dZ. THE measurement ELS_SLIP_SETTLE_TICKS is a
   * guess at — meaningful in v2, where the capture stops before the pass
   * starts
   */
  int32_t diagSettleTicks;

  /* reg 84 READ-ONLY (firmware-owned): signed Z counts summed across the
   * capture
   */
  int32_t diagNetCounts;

  /* reg 86 READ-ONLY (firmware-owned): per-bucket SIGNED sum of dZ. Signed
   * rather than magnitude on purpose — encoder dither cancels, real motion
   * does not, which is exactly the distinction a quiescence test needs and
   * the reason to prefer net displacement over summed |dZ|
   */
  int16_t diagTrace[ELS_DIAG_TRACE_BUCKETS];

  /* reg 136 READ-ONLY (firmware-owned): ticks the capture actually ran, i.e.
   * how long the servo stayed silent after the take-up. Distinct from
   * diagSettleTicks, which is when Z last MOVED
   */
  uint16_t diagCaptureTicks;

  /* reg 137 READ-ONLY (firmware-owned): ELS_DIAG_END_*. A window-full capture
   * did not finish measuring; treat its tail as a floor, not a result
   */
  uint16_t diagEndReason;

  /* reg 138 pads the block to a fixed 128 bytes so its size never depends on
   * which probe is in it
   */
  uint16_t diagReserved[4];
} elsStop_t;

/* ---- the compiler's vote ---- */
static_assert(offsetof(elsStop_t, enable) == 0, "enable moved: schema says register 0");
static_assert(offsetof(elsStop_t, scaleIndex) == 2, "scaleIndex moved: schema says register 1");
static_assert(offsetof(elsStop_t, stopPosition) == 4, "stopPosition moved: schema says register 2");
static_assert(offsetof(elsStop_t, stopDirection) == 8, "stopDirection moved: schema says register 4");
static_assert(offsetof(elsStop_t, active) == 10, "active moved: schema says register 5");
static_assert(offsetof(elsStop_t, threadPitchSteps) == 12, "threadPitchSteps moved: schema says register 6");
static_assert(offsetof(elsStop_t, hysteresis) == 16, "hysteresis moved: schema says register 8");
static_assert(offsetof(elsStop_t, zCountsPerPitch) == 20, "zCountsPerPitch moved: schema says register 10");
static_assert(offsetof(elsStop_t, backlashSteps) == 24, "backlashSteps moved: schema says register 12");
static_assert(offsetof(elsStop_t, latchedZ) == 28, "latchedZ moved: schema says register 14");
static_assert(offsetof(elsStop_t, latchedSpindle) == 32, "latchedSpindle moved: schema says register 16");
static_assert(offsetof(elsStop_t, referenceLatched) == 36, "referenceLatched moved: schema says register 18");
static_assert(offsetof(elsStop_t, takeupPending) == 38, "takeupPending moved: schema says register 19");
static_assert(offsetof(elsStop_t, lastIdealAdvance) == 40, "lastIdealAdvance moved: schema says register 20");
static_assert(offsetof(elsStop_t, lastActualAdvance) == 44, "lastActualAdvance moved: schema says register 22");
static_assert(offsetof(elsStop_t, lastPhaseError) == 48, "lastPhaseError moved: schema says register 24");
static_assert(offsetof(elsStop_t, lastCorrection) == 52, "lastCorrection moved: schema says register 26");
static_assert(offsetof(elsStop_t, protocolVersion) == 56, "protocolVersion moved: schema says register 28");
static_assert(offsetof(elsStop_t, takeupSeq) == 58, "takeupSeq moved: schema says register 29");
static_assert(offsetof(elsStop_t, takeupResult) == 60, "takeupResult moved: schema says register 30");
static_assert(offsetof(elsStop_t, lastTakeupZDelta) == 64, "lastTakeupZDelta moved: schema says register 32");
static_assert(offsetof(elsStop_t, takeupThreshCounts) == 68, "takeupThreshCounts moved: schema says register 34");
static_assert(offsetof(elsStop_t, stepPulseMinCycles) == 72, "stepPulseMinCycles moved: schema says register 36");
static_assert(offsetof(elsStop_t, stepPulseRuntCount) == 76, "stepPulseRuntCount moved: schema says register 38");
static_assert(offsetof(elsStop_t, diagSeq) == 80, "diagSeq moved: schema says register 40");
static_assert(offsetof(elsStop_t, machineMode) == 82, "machineMode moved: schema says register 41");
static_assert(offsetof(elsStop_t, latchSeq) == 84, "latchSeq moved: schema says register 42");
static_assert(offsetof(elsStop_t, phaseOffsetSeq) == 86, "phaseOffsetSeq moved: schema says register 43");
static_assert(offsetof(elsStop_t, phaseOffsetSteps) == 88, "phaseOffsetSteps moved: schema says register 44");
static_assert(offsetof(elsStop_t, stopTriggerSeq) == 92, "stopTriggerSeq moved: schema says register 46");
static_assert(offsetof(elsStop_t, stopTriggerZ) == 96, "stopTriggerZ moved: schema says register 48");
static_assert(offsetof(elsStop_t, stopTriggerZSpeed) == 100, "stopTriggerZSpeed moved: schema says register 50");
static_assert(offsetof(elsStop_t, stopTriggerStepsToGo) == 104, "stopTriggerStepsToGo moved: schema says register 52");
static_assert(offsetof(elsStop_t, stopTriggerSpindleSpeed) == 108, "stopTriggerSpindleSpeed moved: schema says register 54");
static_assert(offsetof(elsStop_t, calCommand) == 112, "calCommand moved: schema says register 56");
static_assert(offsetof(elsStop_t, calSeq) == 114, "calSeq moved: schema says register 57");
static_assert(offsetof(elsStop_t, calResult) == 116, "calResult moved: schema says register 58");
static_assert(offsetof(elsStop_t, latchCommand) == 118, "latchCommand moved: schema says register 59");
static_assert(offsetof(elsStop_t, phaseOffsetCommand) == 120, "phaseOffsetCommand moved: schema says register 60");
static_assert(offsetof(elsStop_t, phaseOffsetPending) == 124, "phaseOffsetPending moved: schema says register 62");
static_assert(offsetof(elsStop_t, bootCommand) == 128, "bootCommand moved: schema says register 64");
static_assert(offsetof(elsStop_t, bootSeq) == 130, "bootSeq moved: schema says register 65");
static_assert(offsetof(elsStop_t, calMeasured) == 132, "calMeasured moved: schema says register 66");
static_assert(offsetof(elsStop_t, calCeilingSteps) == 144, "calCeilingSteps moved: schema says register 72");
static_assert(offsetof(elsStop_t, calMotionThreshCounts) == 148, "calMotionThreshCounts moved: schema says register 74");
static_assert(offsetof(elsStop_t, executionCyclesPeak) == 152, "executionCyclesPeak moved: schema says register 76");
static_assert(offsetof(elsStop_t, diagSchema) == 156, "diagSchema moved: schema says register 78");
static_assert(offsetof(elsStop_t, diagBucketTicks) == 158, "diagBucketTicks moved: schema says register 79");
static_assert(offsetof(elsStop_t, diagBucketCount) == 160, "diagBucketCount moved: schema says register 80");
static_assert(offsetof(elsStop_t, diagSettleTicks) == 164, "diagSettleTicks moved: schema says register 82");
static_assert(offsetof(elsStop_t, diagNetCounts) == 168, "diagNetCounts moved: schema says register 84");
static_assert(offsetof(elsStop_t, diagTrace) == 172, "diagTrace moved: schema says register 86");
static_assert(offsetof(elsStop_t, diagCaptureTicks) == 272, "diagCaptureTicks moved: schema says register 136");
static_assert(offsetof(elsStop_t, diagEndReason) == 274, "diagEndReason moved: schema says register 137");
static_assert(offsetof(elsStop_t, diagReserved) == 276, "diagReserved moved: schema says register 138");
static_assert(sizeof(elsStop_t) == 284, "elsStop_t is not 142 registers");
static_assert(ELS_STOP_HOT_REG_COUNT <= 75, "hot group exceeds its FC3 request budget");
static_assert(ELS_STOP_COLD_REG_COUNT <= 125, "cold group exceeds its FC3 request budget");


/* ======== placement in rampsSharedData_t ======== */

/* rampsSharedData_t itself is hand-written in Ramps.h -- its leading members are not
 * described by any schema -- so where each generated struct sits in it can
 * only be asserted once it exists. Ramps.h expands this immediately after
 * the typedef. The final assert is what makes offsets.json's struct_registers
 * ("where the shared block ends") a compiler-checked number. */
#define RAMPS_GENERATED_ASSERT_PARENT_LAYOUT() \
  static_assert(offsetof(rampsSharedData_t, servo) == 16, "servo is not at register 8 of rampsSharedData_t"); \
  static_assert(offsetof(rampsSharedData_t, scales) == 52, "scales is not at register 26 of rampsSharedData_t"); \
  static_assert(sizeof(((rampsSharedData_t *)0)->scales) == 4 * sizeof(input_t), "scales is not 4 x input_t"); \
  static_assert(offsetof(rampsSharedData_t, fastData) == 148, "fastData is not at register 74 of rampsSharedData_t"); \
  static_assert(offsetof(rampsSharedData_t, elsStop) == 208, "elsStop is not at register 104 of rampsSharedData_t"); \
  static_assert(sizeof(rampsSharedData_t) == 492, "rampsSharedData_t is not 246 registers")

#endif /* RAMPS_GENERATED_H */
