/* GENERATED by tools/genregs.py from registers/els_stop.yaml -- DO NOT EDIT.
 *
 * Edit the schema and regenerate. CI runs `genregs.py --check` and fails the
 * build if this file has drifted from the schema, so a hand-edit here does not
 * survive; it just breaks the build later and further from the cause.
 *
 * The _Static_asserts below are the point of this file. The generator computes
 * offsets from the schema; these make the COMPILER check that arithmetic against
 * what it actually lays out. Emitting both sides of the link from one source is
 * only trustworthy because this disagreement is a build failure.
 */

#ifndef RAMPS_GENERATED_H
#define RAMPS_GENERATED_H

#include <stddef.h>
#include <stdint.h>

#ifndef ELS_DIAG_TRACE_BUCKETS
#define ELS_DIAG_TRACE_BUCKETS 50  /* verified against fw/Core/Inc/Ramps.h */
#endif

#define ELS_STOP_PROTOCOL_VERSION 10u
#define ELS_STOP_TOTAL_REGS 140u
#define ELS_STOP_HOT_REG_BASE 0u
#define ELS_STOP_HOT_REG_COUNT 58u
#define ELS_STOP_COLD_REG_BASE 58u
#define ELS_STOP_COLD_REG_COUNT 82u

/* elsStop_t occupies registers 104..243 of rampsSharedData_t. */
typedef struct {

  /* ---- HOT ----
   * Read as ONE FC3 request every board tick (30 Hz) by
   * Board._refresh_els_stop_snapshot. The quantity being minimised is
   * REQUESTS, not bytes -- each request is an independent chance for the
   * firmware to miss its answering window while the 100 kHz ISR is saturated
   * (2026-08-23: six of six cuts lost comms, every drop a timeout).
   */
  uint16_t enable;                                  /* reg   0  SW write: 1 = enable ELS stop feature */
  uint16_t scaleIndex;                              /* reg   1  SW write: which scale (0-3) is the position reference (Z axis) */
  int32_t stopPosition;                             /* reg   2  SW write: threshold in encoder counts */
  int16_t stopDirection;                            /* reg   4  SW write: 1 = stop when pos >= threshold, -1 = when pos <= threshold */
  uint16_t active;                                  /* reg   5  bidirectional: firmware sets 1 when triggered; SW writes 0 to resume */
  float threadPitchSteps;                           /* reg   6  SW write: leadscrew steps per thread pitch; 0.0f = turning */
  int32_t hysteresis;                               /* reg   8  SW write: counts the carriage must retract before re-enabling */
  float zCountsPerPitch;                            /* reg  10  SW write: Z scale counts per thread pitch; 0.0f = correction disabled */
  uint32_t backlashSteps;                           /* reg  12  SW write: leadscrew backlash take-up magnitude in servo steps */
  int32_t latchedZ;                                 /* reg  14  READ-ONLY (firmware-owned): scales[scaleIndex].position at first trigger of the job */
  int32_t latchedSpindle;                           /* reg  16  READ-ONLY (firmware-owned): scales[0].position at first trigger of the job */
  uint16_t referenceLatched;                        /* reg  18  READ-ONLY (firmware-owned): 0 until the first trigger captures the reference */
  uint16_t takeupPending;                           /* reg  19  READ-ONLY (firmware-owned): 1 while the backlash take-up is in progress */
  float lastIdealAdvance;                           /* reg  20  READ-ONLY (firmware-owned): last resume's ideal advance */
  float lastActualAdvance;                          /* reg  22  READ-ONLY (firmware-owned): last resume's actual advance */
  float lastPhaseError;                             /* reg  24  READ-ONLY (firmware-owned): last resume's phase error */
  float lastCorrection;                             /* reg  26  READ-ONLY (firmware-owned): last resume's correction added to stepsToGo (post-modulo) */
  uint16_t protocolVersion;                         /* reg  28  READ-ONLY (firmware-owned): register-layout version; the UI checks it at connect */
  uint16_t calCommand;                              /* reg  29  bidirectional: SW writes 1 to request a calibration run; firmware clears on consume CLEARED BY FIRMWARE ON CONSUME -- poll calSeq, never this. */
  uint16_t calSeq;                                  /* reg  30  READ-ONLY (firmware-owned): increments once per completed calibration run Monotonic ack; edge-detect it. Sits below everything it counts. */
  uint16_t calResult;                               /* reg  31  READ-ONLY (firmware-owned): ELS_CAL_* outcome code for the run counted by calSeq */
  uint16_t takeupSeq;                               /* reg  32  READ-ONLY (firmware-owned): increments once per completed take-up confirmation Monotonic ack; edge-detect it. Sits below everything it counts. */
  uint16_t takeupResult;                            /* reg  33  READ-ONLY (firmware-owned): ELS_TAKEUP_* outcome code for the take-up counted by takeupSeq */
  int32_t lastTakeupZDelta;                         /* reg  34  READ-ONLY (firmware-owned): measured Z delta of the last take-up, encoder counts */
  uint16_t machineMode;                             /* reg  36  READ-ONLY (firmware-owned): firmware-owned machine mode */
  uint16_t latchCommand;                            /* reg  37  bidirectional: SW writes 1 for a manual reference latch; consumed only while enable == 1 CLEARED BY FIRMWARE ON CONSUME -- poll latchSeq, never this. */
  uint16_t latchSeq;                                /* reg  38  READ-ONLY (firmware-owned): increments once per ACCEPTED manual latch; an absent ack IS the refusal Monotonic ack; edge-detect it. Sits below everything it counts. */
  uint16_t phaseOffsetCommand;                      /* reg  39  bidirectional: SW writes 1 to apply phaseOffsetPending CLEARED BY FIRMWARE ON CONSUME -- poll phaseOffsetSeq, never this. */
  uint16_t phaseOffsetSeq;                          /* reg  40  READ-ONLY (firmware-owned): increments once per accepted phase offset Monotonic ack; edge-detect it. Sits below everything it counts. */
  uint16_t _pad1;        /* generator-emitted alignment, before phaseOffsetPending */
  int32_t phaseOffsetPending;                       /* reg  42  SW write: the offset SW wants applied, in servo steps */
  int32_t phaseOffsetSteps;                         /* reg  44  READ-ONLY (firmware-owned): the offset actually in force */
  uint16_t bootCommand;                             /* reg  46  bidirectional: SW writes 1 to reboot into the bootloader; REFUSED with no ack while enable != 0 CLEARED BY FIRMWARE ON CONSUME -- poll bootSeq, never this. */
  uint16_t bootSeq;                                 /* reg  47  READ-ONLY (firmware-owned): increments once per accepted reboot request Monotonic ack; edge-detect it. Sits below everything it counts. */
  uint16_t stopTriggerSeq;                          /* reg  48  READ-ONLY (firmware-owned): increments once per stop trigger, immediately BEFORE the payload Monotonic ack; edge-detect it. Sits below everything it counts. */
  uint16_t _pad2;        /* generator-emitted alignment, before stopTriggerZ */
  int32_t stopTriggerZ;                             /* reg  50  READ-ONLY (firmware-owned): reference-scale position at the trigger; (settled Z) - this = the coast */
  int32_t stopTriggerZSpeed;                        /* reg  52  READ-ONLY (firmware-owned): reference-scale speed at the trigger, counts/s -- the correction table's x-axis */
  int32_t stopTriggerStepsToGo;                     /* reg  54  READ-ONLY (firmware-owned): servo.stepsToGo at the trigger; nonzero = still commanding motion */
  int32_t stopTriggerSpindleSpeed;                  /* reg  56  READ-ONLY (firmware-owned): scales[0].speed at the trigger, counts/s */

  /* ---- COLD ----
   * Never read on the tick path. Fetched on demand -- at connect, after a
   * calibration run, or when a diagnostic build is being read out.
   */
  int32_t calMeasured[3];                           /* reg  58  READ-ONLY (firmware-owned): per-leg measured take-up, read after a calibration run */
  int32_t calCeilingSteps;                          /* reg  64  SW write: per-leg hard ceiling in servo steps; MACHINE-SPECIFIC, written at setup */
  int32_t calMotionThreshCounts;                    /* reg  66  SW write: counts that constitute motion during calibration; written at setup */
  int32_t takeupThreshCounts;                       /* reg  68  SW write: counts that confirm a take-up; written at setup */
  uint32_t executionCyclesPeak;                     /* reg  70  READ-ONLY (firmware-owned): peak ISR execution time in CPU cycles */
  uint32_t stepPulseMinCycles;                      /* reg  72  READ-ONLY (firmware-owned): narrowest step pulse observed, CPU cycles */
  uint32_t stepPulseRuntCount;                      /* reg  74  READ-ONLY (firmware-owned): count of step pulses below the drive minimum */
  uint16_t diagSchema;                              /* reg  76  READ-ONLY (firmware-owned): which probe is compiled in; 0 = nothing here. A reader MUST check this before interpreting anything below */
  uint16_t diagSeq;                                 /* reg  77  READ-ONLY (firmware-owned): increments once per completed capture Monotonic ack; edge-detect it. Sits below everything it counts. */
  uint16_t diagBucketTicks;                         /* reg  78  READ-ONLY (firmware-owned): ISR ticks summed into each diagTrace bucket; PUBLISHED so the host never assumes the ISR rate */
  uint16_t diagBucketCount;                         /* reg  79  READ-ONLY (firmware-owned): populated diagTrace entries */
  int32_t diagSettleTicks;                          /* reg  80  READ-ONLY (firmware-owned): ticks to settle in the last capture */
  int32_t diagNetCounts;                            /* reg  82  READ-ONLY (firmware-owned): net dZ over the last capture */
  int16_t diagTrace[ELS_DIAG_TRACE_BUCKETS];        /* reg  84  READ-ONLY (firmware-owned): per-bucket SIGNED sum of dZ -- signed so encoder dither cancels and real motion does not */
  uint16_t diagCaptureTicks;                        /* reg 134  READ-ONLY (firmware-owned): total ticks captured */
  uint16_t diagEndReason;                           /* reg 135  READ-ONLY (firmware-owned): why the capture ended */
  uint16_t diagReserved[4];                         /* reg 136  READ-ONLY (firmware-owned): reserved headroom for probe metadata; NOT alignment padding -- the generator emits alignment separately */
} elsStop_t;

/* ---- the compiler's vote ---- */
_Static_assert(offsetof(elsStop_t, enable) == 0, "enable moved: schema says register 0");
_Static_assert(offsetof(elsStop_t, scaleIndex) == 2, "scaleIndex moved: schema says register 1");
_Static_assert(offsetof(elsStop_t, stopPosition) == 4, "stopPosition moved: schema says register 2");
_Static_assert(offsetof(elsStop_t, stopDirection) == 8, "stopDirection moved: schema says register 4");
_Static_assert(offsetof(elsStop_t, active) == 10, "active moved: schema says register 5");
_Static_assert(offsetof(elsStop_t, threadPitchSteps) == 12, "threadPitchSteps moved: schema says register 6");
_Static_assert(offsetof(elsStop_t, hysteresis) == 16, "hysteresis moved: schema says register 8");
_Static_assert(offsetof(elsStop_t, zCountsPerPitch) == 20, "zCountsPerPitch moved: schema says register 10");
_Static_assert(offsetof(elsStop_t, backlashSteps) == 24, "backlashSteps moved: schema says register 12");
_Static_assert(offsetof(elsStop_t, latchedZ) == 28, "latchedZ moved: schema says register 14");
_Static_assert(offsetof(elsStop_t, latchedSpindle) == 32, "latchedSpindle moved: schema says register 16");
_Static_assert(offsetof(elsStop_t, referenceLatched) == 36, "referenceLatched moved: schema says register 18");
_Static_assert(offsetof(elsStop_t, takeupPending) == 38, "takeupPending moved: schema says register 19");
_Static_assert(offsetof(elsStop_t, lastIdealAdvance) == 40, "lastIdealAdvance moved: schema says register 20");
_Static_assert(offsetof(elsStop_t, lastActualAdvance) == 44, "lastActualAdvance moved: schema says register 22");
_Static_assert(offsetof(elsStop_t, lastPhaseError) == 48, "lastPhaseError moved: schema says register 24");
_Static_assert(offsetof(elsStop_t, lastCorrection) == 52, "lastCorrection moved: schema says register 26");
_Static_assert(offsetof(elsStop_t, protocolVersion) == 56, "protocolVersion moved: schema says register 28");
_Static_assert(offsetof(elsStop_t, calCommand) == 58, "calCommand moved: schema says register 29");
_Static_assert(offsetof(elsStop_t, calSeq) == 60, "calSeq moved: schema says register 30");
_Static_assert(offsetof(elsStop_t, calResult) == 62, "calResult moved: schema says register 31");
_Static_assert(offsetof(elsStop_t, takeupSeq) == 64, "takeupSeq moved: schema says register 32");
_Static_assert(offsetof(elsStop_t, takeupResult) == 66, "takeupResult moved: schema says register 33");
_Static_assert(offsetof(elsStop_t, lastTakeupZDelta) == 68, "lastTakeupZDelta moved: schema says register 34");
_Static_assert(offsetof(elsStop_t, machineMode) == 72, "machineMode moved: schema says register 36");
_Static_assert(offsetof(elsStop_t, latchCommand) == 74, "latchCommand moved: schema says register 37");
_Static_assert(offsetof(elsStop_t, latchSeq) == 76, "latchSeq moved: schema says register 38");
_Static_assert(offsetof(elsStop_t, phaseOffsetCommand) == 78, "phaseOffsetCommand moved: schema says register 39");
_Static_assert(offsetof(elsStop_t, phaseOffsetSeq) == 80, "phaseOffsetSeq moved: schema says register 40");
_Static_assert(offsetof(elsStop_t, phaseOffsetPending) == 84, "phaseOffsetPending moved: schema says register 42");
_Static_assert(offsetof(elsStop_t, phaseOffsetSteps) == 88, "phaseOffsetSteps moved: schema says register 44");
_Static_assert(offsetof(elsStop_t, bootCommand) == 92, "bootCommand moved: schema says register 46");
_Static_assert(offsetof(elsStop_t, bootSeq) == 94, "bootSeq moved: schema says register 47");
_Static_assert(offsetof(elsStop_t, stopTriggerSeq) == 96, "stopTriggerSeq moved: schema says register 48");
_Static_assert(offsetof(elsStop_t, stopTriggerZ) == 100, "stopTriggerZ moved: schema says register 50");
_Static_assert(offsetof(elsStop_t, stopTriggerZSpeed) == 104, "stopTriggerZSpeed moved: schema says register 52");
_Static_assert(offsetof(elsStop_t, stopTriggerStepsToGo) == 108, "stopTriggerStepsToGo moved: schema says register 54");
_Static_assert(offsetof(elsStop_t, stopTriggerSpindleSpeed) == 112, "stopTriggerSpindleSpeed moved: schema says register 56");
_Static_assert(offsetof(elsStop_t, calMeasured) == 116, "calMeasured moved: schema says register 58");
_Static_assert(offsetof(elsStop_t, calCeilingSteps) == 128, "calCeilingSteps moved: schema says register 64");
_Static_assert(offsetof(elsStop_t, calMotionThreshCounts) == 132, "calMotionThreshCounts moved: schema says register 66");
_Static_assert(offsetof(elsStop_t, takeupThreshCounts) == 136, "takeupThreshCounts moved: schema says register 68");
_Static_assert(offsetof(elsStop_t, executionCyclesPeak) == 140, "executionCyclesPeak moved: schema says register 70");
_Static_assert(offsetof(elsStop_t, stepPulseMinCycles) == 144, "stepPulseMinCycles moved: schema says register 72");
_Static_assert(offsetof(elsStop_t, stepPulseRuntCount) == 148, "stepPulseRuntCount moved: schema says register 74");
_Static_assert(offsetof(elsStop_t, diagSchema) == 152, "diagSchema moved: schema says register 76");
_Static_assert(offsetof(elsStop_t, diagSeq) == 154, "diagSeq moved: schema says register 77");
_Static_assert(offsetof(elsStop_t, diagBucketTicks) == 156, "diagBucketTicks moved: schema says register 78");
_Static_assert(offsetof(elsStop_t, diagBucketCount) == 158, "diagBucketCount moved: schema says register 79");
_Static_assert(offsetof(elsStop_t, diagSettleTicks) == 160, "diagSettleTicks moved: schema says register 80");
_Static_assert(offsetof(elsStop_t, diagNetCounts) == 164, "diagNetCounts moved: schema says register 82");
_Static_assert(offsetof(elsStop_t, diagTrace) == 168, "diagTrace moved: schema says register 84");
_Static_assert(offsetof(elsStop_t, diagCaptureTicks) == 268, "diagCaptureTicks moved: schema says register 134");
_Static_assert(offsetof(elsStop_t, diagEndReason) == 270, "diagEndReason moved: schema says register 135");
_Static_assert(offsetof(elsStop_t, diagReserved) == 272, "diagReserved moved: schema says register 136");
_Static_assert(sizeof(elsStop_t) == 280, "elsStop_t is not 140 registers");
_Static_assert(ELS_STOP_HOT_REG_COUNT <= 75, "hot group exceeds its FC3 request budget");
_Static_assert(ELS_STOP_COLD_REG_COUNT <= 125, "cold group exceeds its FC3 request budget");

#endif /* RAMPS_GENERATED_H */
