"""GENERATED by tools/genregs.py from registers/fast_data.yaml -- DO NOT EDIT.

Offsets are fastData-relative registers. Add FAST_DATA_BASE for an absolute
address in rampsSharedData_t. No hand-placed padding: alignment pads are
emitted into the format strings below, which is the whole point.
"""

import struct

FAST_DATA_BASE = 74
TOTAL_REGISTERS = 30

ALL_BASE = 0
ALL_COUNT = 30
ALL_FORMAT = "<IIIf4i4iIIH2x"
ALL_FIELDS = [
    "servoCurrent",
    "servoDesired",
    "stepsToGo",
    "servoSpeed",
    "scaleCurrent",
    "scaleSpeed",
    "cycles",
    "executionInterval",
    "servoMode",
]
ALL_LAYOUT = [
    ("servoCurrent", 1),
    ("servoDesired", 1),
    ("stepsToGo", 1),
    ("servoSpeed", 1),
    ("scaleCurrent", 4),
    ("scaleSpeed", 4),
    ("cycles", 1),
    ("executionInterval", 1),
    ("servoMode", 1),
]

OFFSETS = {
    "servoCurrent": 0,
    "servoDesired": 2,
    "stepsToGo": 4,
    "servoSpeed": 6,
    "scaleCurrent": 8,
    "scaleSpeed": 16,
    "cycles": 24,
    "executionInterval": 26,
    "servoMode": 28,
}


def _decode(raw, fmt, layout):
    """Turn one FC3 span into {field: value}, arrays regrouped.

    A group is decoded from its OWN format string, so a field added to
    the schema cannot shift the columns of a reader that was not
    regenerated -- the format and the layout move together or not at all.
    """
    if len(raw) * 2 != struct.calcsize(fmt):
        raise ValueError(
            "span is %d registers, format wants %d -- refusing to decode"
            % (len(raw), struct.calcsize(fmt) // 2))
    values = list(struct.unpack(fmt, struct.pack("<%dH" % len(raw), *raw)))
    out = {}
    for name, count in layout:
        if count > 1:
            out[name] = [values.pop(0) for _ in range(count)]
        else:
            out[name] = values.pop(0)
    if values:
        raise ValueError("%d values left over after decode" % len(values))
    return out


def decode_all(raw):
    return _decode(raw, ALL_FORMAT, ALL_LAYOUT)

DEFINITION = """
typedef struct {
  uint32_t servoCurrent;
  uint32_t servoDesired;
  uint32_t stepsToGo;
  float servoSpeed;
  int32_t scaleCurrent[4];
  int32_t scaleSpeed[4];
  uint32_t cycles;
  uint32_t executionInterval;
  uint16_t servoMode;
  uint16_t _pad1;
} fastData_t;
"""
