"""GENERATED by tools/genregs.py from registers/input.yaml -- DO NOT EDIT.

Offsets are input-relative registers. Add INPUT_BASE for an absolute
address in rampsSharedData_t. No hand-placed padding: alignment pads are
emitted into the format strings below, which is the whole point.

input_t is the element type of scales[4]: element i
starts at INPUT_BASE + i * TOTAL_REGISTERS.
"""

import struct

INPUT_BASE = 26
INPUT_COUNT = 4
TOTAL_REGISTERS = 12

ALL_BASE = 0
ALL_COUNT = 12
ALL_FORMAT = "<IiiiiHh"
ALL_FIELDS = [
    "timerHandleSlot",
    "position",
    "speed",
    "syncRatioNum",
    "syncRatioDen",
    "syncEnable",
    "scaleDir",
]
ALL_LAYOUT = [
    ("timerHandleSlot", 1),
    ("position", 1),
    ("speed", 1),
    ("syncRatioNum", 1),
    ("syncRatioDen", 1),
    ("syncEnable", 1),
    ("scaleDir", 1),
]

OFFSETS = {
    "timerHandleSlot": 0,
    "position": 2,
    "speed": 4,
    "syncRatioNum": 6,
    "syncRatioDen": 8,
    "syncEnable": 10,
    "scaleDir": 11,
}


def _decode(raw, fmt, layout):
    """Turn one FC3 span into {field: value}, arrays regrouped.

    A group is decoded from its OWN format string, so a field added to
    the schema cannot shift the columns of a reader that was not
    regenerated -- the format and the layout move together or not at all.
    """
    if len(raw) * 2 != struct.calcsize(fmt):
        raise ValueError(
            "span is %d registers, format wants %d -- refusing to decode"
            % (len(raw), struct.calcsize(fmt) // 2))
    values = list(struct.unpack(fmt, struct.pack("<%dH" % len(raw), *raw)))
    out = {}
    for name, count in layout:
        if count > 1:
            out[name] = [values.pop(0) for _ in range(count)]
        else:
            out[name] = values.pop(0)
    if values:
        raise ValueError("%d values left over after decode" % len(values))
    return out


def decode_all(raw):
    return _decode(raw, ALL_FORMAT, ALL_LAYOUT)

DEFINITION = """
typedef struct {
  uint32_t timerHandleSlot;
  int32_t position;
  int32_t speed;
  int32_t syncRatioNum;
  int32_t syncRatioDen;
  uint16_t syncEnable;
  int16_t scaleDir;
} input_t;
"""
