"""GENERATED by tools/genregs.py from registers/servo.yaml -- DO NOT EDIT.

Offsets are servo-relative registers. Add SERVO_BASE for an absolute
address in rampsSharedData_t. No hand-placed padding: alignment pads are
emitted into the format strings below, which is the whole point.
"""

import struct

SERVO_BASE = 8
TOTAL_REGISTERS = 18

ALL_BASE = 0
ALL_COUNT = 18
ALL_FORMAT = "<ffffiIIIh2x"
ALL_FIELDS = [
    "maxSpeed",
    "currentSpeed",
    "jogSpeed",
    "acceleration",
    "stepsToGo",
    "destinationSteps",
    "currentSteps",
    "desiredSteps",
    "servoDir",
]
ALL_LAYOUT = [
    ("maxSpeed", 1),
    ("currentSpeed", 1),
    ("jogSpeed", 1),
    ("acceleration", 1),
    ("stepsToGo", 1),
    ("destinationSteps", 1),
    ("currentSteps", 1),
    ("desiredSteps", 1),
    ("servoDir", 1),
]

OFFSETS = {
    "maxSpeed": 0,
    "currentSpeed": 2,
    "jogSpeed": 4,
    "acceleration": 6,
    "stepsToGo": 8,
    "destinationSteps": 10,
    "currentSteps": 12,
    "desiredSteps": 14,
    "servoDir": 16,
}


def _decode(raw, fmt, layout):
    """Turn one FC3 span into {field: value}, arrays regrouped.

    A group is decoded from its OWN format string, so a field added to
    the schema cannot shift the columns of a reader that was not
    regenerated -- the format and the layout move together or not at all.
    """
    if len(raw) * 2 != struct.calcsize(fmt):
        raise ValueError(
            "span is %d registers, format wants %d -- refusing to decode"
            % (len(raw), struct.calcsize(fmt) // 2))
    values = list(struct.unpack(fmt, struct.pack("<%dH" % len(raw), *raw)))
    out = {}
    for name, count in layout:
        if count > 1:
            out[name] = [values.pop(0) for _ in range(count)]
        else:
            out[name] = values.pop(0)
    if values:
        raise ValueError("%d values left over after decode" % len(values))
    return out


def decode_all(raw):
    return _decode(raw, ALL_FORMAT, ALL_LAYOUT)

DEFINITION = """
typedef struct {
  float maxSpeed;
  float currentSpeed;
  float jogSpeed;
  float acceleration;
  int32_t stepsToGo;
  uint32_t destinationSteps;
  uint32_t currentSteps;
  uint32_t desiredSteps;
  int16_t servoDir;
  uint16_t _pad1;
} servo_t;
"""
