/* GENERATED by tools/genpins.py from the board's design export -- DO NOT EDIT.
 *
 * Regenerate:      python3 tools/genpins.py render
 * Re-vendor from a new kicad-reflex commit:
 *   python3 tools/genpins.py vendor --board provvedo --kicad-reflex <path-to-kicad-reflex> --rev <rev>
 *
 * from kicad-reflex 5ca840d8c620, 2026-09-26 (pinout/provvedo.json)
 *
 * Design source: ipc356 reader, third-party/provvedo-v1.2/netlist.ipc, sha256 14b9444c4ef84395...
 * MCU: U6, STM32F411CEUx
 *
 * Nothing includes this header yet. The per-board firmware build
 * is what wires Ramps.h to consume it; until then this file
 * exists so tools/genpins.py --check-handwritten can hold the hand-copied
 * pins in fw/Core/Inc/Ramps.h, fw/Core/Inc/main.h, fw/Core/Src/tim.c and
 * fw/Core/Src/usart.c to what the design actually says.
 */
#ifndef REFLEX_BOARD_PROVVEDO_PINS_H
#define REFLEX_BOARD_PROVVEDO_PINS_H

#define BOARD_NAME "provvedo"
#define BOARD_MCU_PART "STM32F411CEUx"

/* Device check: board 'provvedo' has MCU part STM32F411CEUx, CMSIS device
 * macro STM32F411xE. If a cross build defines a DIFFERENT device macro this
 * generator knows about, it is compiling THIS board's pins for the wrong
 * chip -- fail loudly rather than silently miswiring GPIOs. The emulator
 * build always defines STM32F411xE for every board
 * (fw/emulator/CMakeLists.txt) -- the same macro provvedo expects -- so
 * it can never trip this guard. An MCU part this generator has not been
 * taught (see PART_TO_CMSIS_MACRO) gets a comment instead of a guard, so
 * it cannot misfire on a device it does not recognise. */
#if defined(STM32F411xE)
/* OK: matches board part STM32F411CEUx */
#elif defined(STM32F413xx)
#error "pins.h: built for STM32F413xx, but board 'provvedo' is STM32F411CEUx (expects STM32F411xE) -- wrong pins.h for this cross build"
#endif

/* ---- named GPIO nets, in pin-number order ---- */

/* OSCIN -- pin 5, PH0 */
#define BOARD_OSCIN_PORT         GPIOH
#define BOARD_OSCIN_PIN          GPIO_PIN_0
#define BOARD_OSCIN_PIN_NUM      0U

/* OSCOUT -- pin 6, PH1 */
#define BOARD_OSCOUT_PORT        GPIOH
#define BOARD_OSCOUT_PIN         GPIO_PIN_1
#define BOARD_OSCOUT_PIN_NUM     1U

/* MTR_STEP -- pin 10, PA0 */
#define BOARD_MTR_STEP_PORT      GPIOA
#define BOARD_MTR_STEP_PIN       GPIO_PIN_0
#define BOARD_MTR_STEP_PIN_NUM   0U

/* SPARE_1 -- pin 11, PA1 */
#define BOARD_SPARE_1_PORT       GPIOA
#define BOARD_SPARE_1_PIN        GPIO_PIN_1
#define BOARD_SPARE_1_PIN_NUM    1U

/* SPARE_2 -- pin 13, PA3 */
#define BOARD_SPARE_2_PORT       GPIOA
#define BOARD_SPARE_2_PIN        GPIO_PIN_3
#define BOARD_SPARE_2_PIN_NUM    3U

/* SPARE_3 -- pin 14, PA4 */
#define BOARD_SPARE_3_PORT       GPIOA
#define BOARD_SPARE_3_PIN        GPIO_PIN_4
#define BOARD_SPARE_3_PIN_NUM    4U

/* ENC2A -- pin 15, PA5 */
#define BOARD_ENC2A_PORT         GPIOA
#define BOARD_ENC2A_PIN          GPIO_PIN_5
#define BOARD_ENC2A_PIN_NUM      5U

/* ENC3A -- pin 16, PA6 */
#define BOARD_ENC3A_PORT         GPIOA
#define BOARD_ENC3A_PIN          GPIO_PIN_6
#define BOARD_ENC3A_PIN_NUM      6U

/* ENC3B -- pin 17, PA7 */
#define BOARD_ENC3B_PORT         GPIOA
#define BOARD_ENC3B_PIN          GPIO_PIN_7
#define BOARD_ENC3B_PIN_NUM      7U

/* SPARE_4 -- pin 18, PB0 */
#define BOARD_SPARE_4_PORT       GPIOB
#define BOARD_SPARE_4_PIN        GPIO_PIN_0
#define BOARD_SPARE_4_PIN_NUM    0U

/* USR_LED -- pin 25, PB12 */
#define BOARD_USR_LED_PORT       GPIOB
#define BOARD_USR_LED_PIN        GPIO_PIN_12
#define BOARD_USR_LED_PIN_NUM    12U

/* MTR_DIR -- pin 27, PB14 */
#define BOARD_MTR_DIR_PORT       GPIOB
#define BOARD_MTR_DIR_PIN        GPIO_PIN_14
#define BOARD_MTR_DIR_PIN_NUM    14U

/* MTR_ENA -- pin 28, PB15 */
#define BOARD_MTR_ENA_PORT       GPIOB
#define BOARD_MTR_ENA_PIN        GPIO_PIN_15
#define BOARD_MTR_ENA_PIN_NUM    15U

/* ENC1A -- pin 29, PA8 */
#define BOARD_ENC1A_PORT         GPIOA
#define BOARD_ENC1A_PIN          GPIO_PIN_8
#define BOARD_ENC1A_PIN_NUM      8U

/* ENC1B -- pin 30, PA9 */
#define BOARD_ENC1B_PORT         GPIOA
#define BOARD_ENC1B_PIN          GPIO_PIN_9
#define BOARD_ENC1B_PIN_NUM      9U

/* RXD -- pin 31, PA10 */
#define BOARD_RXD_PORT           GPIOA
#define BOARD_RXD_PIN            GPIO_PIN_10
#define BOARD_RXD_PIN_NUM        10U

/* TMS/SWDIO -- pin 34, PA13 */
#define BOARD_TMS_SWDIO_PORT     GPIOA
#define BOARD_TMS_SWDIO_PIN      GPIO_PIN_13
#define BOARD_TMS_SWDIO_PIN_NUM  13U

/* TCLK/SWCLK -- pin 37, PA14 */
#define BOARD_TCLK_SWCLK_PORT    GPIOA
#define BOARD_TCLK_SWCLK_PIN     GPIO_PIN_14
#define BOARD_TCLK_SWCLK_PIN_NUM 14U

/* TXD -- pin 38, PA15 */
#define BOARD_TXD_PORT           GPIOA
#define BOARD_TXD_PIN            GPIO_PIN_15
#define BOARD_TXD_PIN_NUM        15U

/* ENC2B -- pin 39, PB3 */
#define BOARD_ENC2B_PORT         GPIOB
#define BOARD_ENC2B_PIN          GPIO_PIN_3
#define BOARD_ENC2B_PIN_NUM      3U

/* ENC4A -- pin 42, PB6 */
#define BOARD_ENC4A_PORT         GPIOB
#define BOARD_ENC4A_PIN          GPIO_PIN_6
#define BOARD_ENC4A_PIN_NUM      6U

/* ENC4B -- pin 43, PB7 */
#define BOARD_ENC4B_PORT         GPIOB
#define BOARD_ENC4B_PIN          GPIO_PIN_7
#define BOARD_ENC4B_PIN_NUM      7U

/* Unconnected GPIOs (present, not brought out to a net): PC13, PC14, PC15, PA2, PB1, PB2, PB10, PB13, PA11, PA12, PB4, PB5, PB8, PB9 */
/* Unnamed GPIOs (present, no net name assigned yet):     (none) */

#endif /* REFLEX_BOARD_PROVVEDO_PINS_H */
