"""Generate docs/reference/index.md from the in-app help corpus.

The machine ships ~35 help topics under ui/reflex/help/, rendered by the `?`
buttons on the settings screens. Those are the REFERENCE layer: what one field
means. The user guide is the NARRATIVE layer: how to do a job. Neither should
copy the other.

This index is the seam. It is generated so it cannot list a topic that was
deleted or miss one that was added -- which is exactly what a hand-maintained
list of 35 files does within a release.

The topics are LINKED rather than inlined. MkDocs cannot reference a file
outside its docs_dir, and the alternative (copying them in at build time) would
put two copies of every help topic in the repo, which is the drift this whole
arrangement exists to avoid.

Run (from ui/):

    ./.venv/bin/python ../tools/gen_reference_index.py [--check]
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
HELP = os.path.join(REPO, "ui", "reflex", "help")
OUT = os.path.join(REPO, "docs", "reference", "index.md")
BLOB = "https://github.com/Funkenjaeger/reflex/blob/main/ui/reflex/help/"

# Grouping, so 35 topics are not one flat wall. A file in no group lands in
# "Everything else" rather than vanishing -- an index that silently drops a
# topic is worse than an untidy one.
GROUPS = [
    ("Electronic leadscrew", lambda n: n.startswith("els_")),
    ("Axes and scales", lambda n: n in {
        "axis_name", "scales", "scale_input", "spindle_mode", "transform_type",
        "sync_ratio", "units_per_turn", "angle_degrees", "position_tolerance"}),
    ("Servo and leadscrew", lambda n: n in {
        "servo_gearing", "servo_max_speed", "servo_acceleration",
        "lead_screw_pitch", "weights"}),
    ("Display", lambda n: n in {
        "colors", "display_font", "font_size", "format_digits", "ui_theme",
        "hide_mouse_cursor", "volume"}),
    ("System", lambda n: n in {
        "network_connection", "enable_wifi", "software_update",
        "system_storage", "error_reporting"}),
]

HEAD = """<!-- GENERATED by tools/gen_reference_index.py -- do not edit by hand. -->

# Reference

The machine carries its own help. Every settings screen has a **?** that opens
the topic for the field you are looking at, and those topics are the reference
layer: what one setting means, what a bad value does, and what to check.

This page indexes them. The topics themselves live with the software so they
ship to the machine, and they are linked here rather than copied — one source,
no drift.

!!! tip "On the machine, you do not need this page"
    Press the **?**. This index exists for reading the corpus away from the
    lathe, and for finding a topic by name.

"""


def title_of(path, name):
    with open(path, encoding="utf-8") as f:
        text = f.read()
    m = re.search(r"^#\s+(.+)$", text, re.M)
    if m:
        return m.group(1).strip()
    # Some topics use a Setext heading (title, then ===).
    m = re.search(r"^(.+)\n=+\s*$", text, re.M)
    if m:
        return m.group(1).strip()
    return name.replace("_", " ").capitalize()


def render():
    names = sorted(f[:-3] for f in os.listdir(HELP) if f.endswith(".md"))
    assert names, "no help topics found in %s" % HELP

    placed = set()
    parts = [HEAD]
    for heading, belongs in GROUPS:
        rows = [n for n in names if belongs(n) and n not in placed]
        if not rows:
            continue
        placed.update(rows)
        parts.append(f"## {heading}\n\n")
        for n in rows:
            path = os.path.join(HELP, n + ".md")
            size = os.path.getsize(path)
            t = title_of(path, n)
            note = "" if size else "  *(topic is empty)*"
            parts.append(f"- [{t}]({BLOB}{n}.md) &nbsp;`{n}`{note}\n")
        parts.append("\n")

    rest = [n for n in names if n not in placed]
    if rest:
        parts.append("## Everything else\n\n")
        for n in rest:
            path = os.path.join(HELP, n + ".md")
            parts.append(f"- [{title_of(path, n)}]({BLOB}{n}.md) &nbsp;`{n}`\n")
        parts.append("\n")

    parts.append(f"---\n\n{len(names)} topics.\n")
    return "".join(parts)


def main():
    text = render()
    existing = None
    if os.path.exists(OUT):
        with open(OUT, encoding="utf-8", newline="") as f:
            existing = f.read()
    if "--check" in sys.argv:
        if existing != text:
            raise SystemExit(
                "docs/reference/index.md is stale -- a help topic was added, "
                "removed or retitled. Run:\n"
                "    ./.venv/bin/python ../tools/gen_reference_index.py")
        print("reference index is current")
        return
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote {OUT}{' (unchanged)' if existing == text else ''}")


if __name__ == "__main__":
    main()
