# BuildRev.cmake -- generate reflex_build_rev.h from the git checkout.
#
# Run at BUILD time (not configure time) by a custom target, so the rev in the
# binary is the rev of the tree the binary was built from, not of the tree
# that last ran cmake. Writes the header only when its content changes, so an
# unchanged rev does not rebuild every translation unit that includes it.
#
#   cmake -DOUT=<path/reflex_build_rev.h> -DSRC=<repo dir> -P BuildRev.cmake
#
# The value is what the identity window publishes as idBuildRevLo/Hi and
# idBuildDirty (els_identity.h), and what the image header carries as
# buildRev: a 7-hex-digit git short rev (28 bits) and a dirty flag computed
# the way scripts/flash.sh computes it (tracked changes, staged or not).
# No git, or not a repo, yields rev 0 with DIRTY 1: an unknown build must
# never look like a clean, identifiable one.

if(NOT DEFINED OUT OR NOT DEFINED SRC)
    message(FATAL_ERROR "BuildRev.cmake needs -DOUT=<header> -DSRC=<repo dir>")
endif()

set(REV_HEX "0")
set(DIRTY 1)

find_program(GIT_EXE git)
if(GIT_EXE)
    execute_process(
        COMMAND ${GIT_EXE} -C ${SRC} rev-parse --short=7 HEAD
        OUTPUT_VARIABLE rev_out OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE rev_rc ERROR_QUIET)
    if(rev_rc EQUAL 0 AND rev_out MATCHES "^[0-9a-f]+$")
        set(REV_HEX ${rev_out})
        execute_process(COMMAND ${GIT_EXE} -C ${SRC} diff --quiet
                        RESULT_VARIABLE unstaged_rc ERROR_QUIET)
        execute_process(COMMAND ${GIT_EXE} -C ${SRC} diff --cached --quiet
                        RESULT_VARIABLE staged_rc ERROR_QUIET)
        if(unstaged_rc EQUAL 0 AND staged_rc EQUAL 0)
            set(DIRTY 0)
        endif()
    endif()
endif()

string(LENGTH "${REV_HEX}" rev_len)
if(rev_len GREATER 7)
    # --short=7 can return more digits when 7 is ambiguous; the window has
    # 28 bits, so keep the leading 7 the way `git rev-parse --short=7` names
    # the commit to a human.
    string(SUBSTRING "${REV_HEX}" 0 7 REV_HEX)
endif()

set(content "/* Generated by cmake/BuildRev.cmake -- do not edit, do not commit. */
#ifndef REFLEX_BUILD_REV_H
#define REFLEX_BUILD_REV_H
#define REFLEX_BUILD_REV   0x${REV_HEX}u
#define REFLEX_BUILD_DIRTY ${DIRTY}u
#define REFLEX_BUILD_REV_STR \"${REV_HEX}\"
#endif
")

set(existing "")
if(EXISTS ${OUT})
    file(READ ${OUT} existing)
endif()
if(NOT existing STREQUAL content)
    get_filename_component(out_dir ${OUT} DIRECTORY)
    file(MAKE_DIRECTORY ${out_dir})
    file(WRITE ${OUT} "${content}")
    message(STATUS "build rev ${REV_HEX} dirty=${DIRTY} -> ${OUT}")
endif()
